/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidndk_JniTest */

#ifndef _Included_com_androidndk_JniTest
#define _Included_com_androidndk_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androidndk_JniTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidndk_JniTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
