/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidndk_ShowInfo */

#ifndef _Included_com_androidndk_ShowInfo
#define _Included_com_androidndk_ShowInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androidndk_ShowInfo
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidndk_ShowInfo_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
